-- =============================================================================
-- FASE 1: CAMBIOS EN BASE DE DATOS - MÓDULO DE FACTURACIÓN
-- =============================================================================

CREATE TABLE ODO_USUARIO_PUNTOS_EXPEDICION (
    USUARIO_PUNTO_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO_ID             NUMBER NOT NULL,
    TIMBRADO_ID            NUMBER NOT NULL,
    ACTIVO                 CHAR(1) DEFAULT 'S' CHECK (ACTIVO IN ('S', 'N')),
    FECHA_ASIGNACION       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    ASIGNADO_POR           NUMBER,
    FECHA_MODIFICACION     TIMESTAMP WITH TIME ZONE,
    MODIFICADO_POR         NUMBER,
    
    CONSTRAINT FK_UPE_USUARIO FOREIGN KEY (USUARIO_ID) 
        REFERENCES ODO_USUARIOS(USUARIO_ID),
    CONSTRAINT FK_UPE_TIMBRADO FOREIGN KEY (TIMBRADO_ID) 
        REFERENCES ODO_TIMBRADOS(TIMBRADO_ID),
    CONSTRAINT FK_UPE_ASIGNADO_POR FOREIGN KEY (ASIGNADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID),
    CONSTRAINT FK_UPE_MODIFICADO_POR FOREIGN KEY (MODIFICADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID),
    CONSTRAINT UQ_USUARIO_TIMBRADO UNIQUE (USUARIO_ID, TIMBRADO_ID)
)
;;;
COMMENT ON TABLE ODO_USUARIO_PUNTOS_EXPEDICION IS 'Asignación de puntos de expedición (timbrados) a usuarios para facturación'
;;;
COMMENT ON COLUMN ODO_USUARIO_PUNTOS_EXPEDICION.USUARIO_PUNTO_ID IS 'ID único de la asignación'
;;;
COMMENT ON COLUMN ODO_USUARIO_PUNTOS_EXPEDICION.USUARIO_ID IS 'Usuario que tiene asignado el punto de expedición'
;;;
COMMENT ON COLUMN ODO_USUARIO_PUNTOS_EXPEDICION.TIMBRADO_ID IS 'Timbrado (punto de expedición) asignado'
;;;
COMMENT ON COLUMN ODO_USUARIO_PUNTOS_EXPEDICION.ACTIVO IS 'Indica si la asignación está activa (S/N)'
;;;
CREATE INDEX IDX_FACTURAS_ESTADO ON ODO_FACTURAS(ESTADO)
;;;
CREATE INDEX IDX_FACTURAS_PACIENTE ON ODO_FACTURAS(PACIENTE_ID)
;;;
CREATE INDEX IDX_FACTURAS_FECHA ON ODO_FACTURAS(FECHA_EMISION)
;;;
CREATE INDEX IDX_FACTURAS_TIMBRADO ON ODO_FACTURAS(TIMBRADO_ID)
;;;
CREATE INDEX IDX_FACTURAS_EMPRESA ON ODO_FACTURAS(EMPRESA_ID)
;;;
CREATE INDEX IDX_FACTURAS_SUCURSAL ON ODO_FACTURAS(SUCURSAL_ID)
;;;
CREATE INDEX IDX_PAGOS_FACTURA ON ODO_PAGOS(FACTURA_ID)
;;;
CREATE INDEX IDX_PAGOS_PACIENTE ON ODO_PAGOS(PACIENTE_ID)
;;;
CREATE INDEX IDX_PAGOS_FECHA ON ODO_PAGOS(FECHA_PAGO)
;;;
CREATE INDEX IDX_PAGOS_METODO ON ODO_PAGOS(METODO_PAGO)
;;;
CREATE INDEX IDX_DETALLES_FACTURA ON ODO_DETALLES_FACTURA(FACTURA_ID)
;;;
CREATE INDEX IDX_DETALLES_TRATAMIENTO ON ODO_DETALLES_FACTURA(TRATAMIENTO_PACIENTE_ID)
;;;
CREATE INDEX IDX_TIMBRADOS_EMPRESA ON ODO_TIMBRADOS(EMPRESA_ID)
;;;
CREATE INDEX IDX_TIMBRADOS_ACTIVO ON ODO_TIMBRADOS(ACTIVO)
;;;
CREATE INDEX IDX_TIMBRADOS_VENCIMIENTO ON ODO_TIMBRADOS(FECHA_VENCIMIENTO)
;;;
