-- =============================================================================
-- MÓDULO DE COMPRAS - CREACIÓN DE TABLAS
-- =============================================================================

-- ============================================================================
-- TABLA: ODO_CATEGORIAS_ARTICULOS
-- Categorías de artículos/materiales (instrumental, medicamentos, etc.)
-- ============================================================================
CREATE TABLE ODO_CATEGORIAS_ARTICULOS (
    CATEGORIA_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE                 VARCHAR2(100) NOT NULL UNIQUE,
    DESCRIPCION            VARCHAR2(500),
    ACTIVO                 CHAR(1) DEFAULT 'S' CHECK (ACTIVO IN ('S', 'N')),
    FECHA_CREACION         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    CREADO_POR             NUMBER,
    FECHA_MODIFICACION     TIMESTAMP WITH TIME ZONE,
    MODIFICADO_POR         NUMBER,
    
    CONSTRAINT FK_CAT_CREADO_POR FOREIGN KEY (CREADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID),
    CONSTRAINT FK_CAT_MODIFICADO_POR FOREIGN KEY (MODIFICADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID)
)
;;;
COMMENT ON TABLE ODO_CATEGORIAS_ARTICULOS IS 'Categorías de artículos/materiales disponibles'
;;;
COMMENT ON COLUMN ODO_CATEGORIAS_ARTICULOS.CATEGORIA_ID IS 'ID único de la categoría'
;;;
COMMENT ON COLUMN ODO_CATEGORIAS_ARTICULOS.NOMBRE IS 'Nombre de la categoría'
;;;

-- ============================================================================
-- TABLA: ODO_ARTICULOS
-- Artículos/materiales que se pueden comprar
-- ============================================================================
CREATE TABLE ODO_ARTICULOS (
    ARTICULO_ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO                 VARCHAR2(50) NOT NULL UNIQUE,
    NOMBRE                 VARCHAR2(200) NOT NULL,
    DESCRIPCION            VARCHAR2(1000),
    CATEGORIA_ID           NUMBER NOT NULL,
    UNIDAD_MEDIDA          VARCHAR2(20) NOT NULL, -- unidad, paquete, caja, etc.
    COSTO_UNITARIO         NUMBER(12,2) DEFAULT 0,
    PRECIO_VENTA           NUMBER(12,2) DEFAULT 0,
    CANTIDAD_MINIMA        NUMBER DEFAULT 0,
    CANTIDAD_MAXIMA        NUMBER DEFAULT 0,
    ACTIVO                 CHAR(1) DEFAULT 'S' CHECK (ACTIVO IN ('S', 'N')),
    FECHA_CREACION         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    CREADO_POR             NUMBER,
    FECHA_MODIFICACION     TIMESTAMP WITH TIME ZONE,
    MODIFICADO_POR         NUMBER,
    
    CONSTRAINT FK_ART_CATEGORIA FOREIGN KEY (CATEGORIA_ID)
        REFERENCES ODO_CATEGORIAS_ARTICULOS(CATEGORIA_ID),
    CONSTRAINT FK_ART_CREADO_POR FOREIGN KEY (CREADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID),
    CONSTRAINT FK_ART_MODIFICADO_POR FOREIGN KEY (MODIFICADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID),
    CONSTRAINT CHK_COSTO_POSITIVO CHECK (COSTO_UNITARIO >= 0),
    CONSTRAINT CHK_PRECIO_POSITIVO CHECK (PRECIO_VENTA >= 0)
)
;;;
COMMENT ON TABLE ODO_ARTICULOS IS 'Artículos/materiales que se pueden comprar para tratamientos'
;;;
COMMENT ON COLUMN ODO_ARTICULOS.CODIGO IS 'Código único del artículo'
;;;

-- ============================================================================
-- TABLA: ODO_PROVEEDORES
-- Proveedores/vendedores de artículos
-- ============================================================================
CREATE TABLE ODO_PROVEEDORES (
    PROVEEDOR_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE                 VARCHAR2(200) NOT NULL,
    RUC                    VARCHAR2(20),
    NOMBRE_CONTACTO        VARCHAR2(150),
    TELEFONO               VARCHAR2(20),
    EMAIL                  VARCHAR2(100),
    DIRECCION              VARCHAR2(500),
    CIUDAD                 VARCHAR2(100),
    DEPARTAMENTO           VARCHAR2(100),
    PAIS                   VARCHAR2(100) DEFAULT 'Paraguay',
    CONDICIONES_PAGO       VARCHAR2(500),
    MONEDA                 VARCHAR2(10) DEFAULT 'PYG',
    ACTIVO                 CHAR(1) DEFAULT 'S' CHECK (ACTIVO IN ('S', 'N')),
    FECHA_CREACION         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    CREADO_POR             NUMBER,
    FECHA_MODIFICACION     TIMESTAMP WITH TIME ZONE,
    MODIFICADO_POR         NUMBER,
    
    CONSTRAINT FK_PROV_CREADO_POR FOREIGN KEY (CREADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID),
    CONSTRAINT FK_PROV_MODIFICADO_POR FOREIGN KEY (MODIFICADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID)
)
;;;
COMMENT ON TABLE ODO_PROVEEDORES IS 'Proveedores/vendedores de artículos'
;;;
COMMENT ON COLUMN ODO_PROVEEDORES.PROVEEDOR_ID IS 'ID único del proveedor'
;;;

-- ============================================================================
-- TABLA: ODO_ORDENES_COMPRA
-- Órdenes de compra (solicitudes)
-- ============================================================================
CREATE TABLE ODO_ORDENES_COMPRA (
    ORDEN_COMPRA_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO_ORDEN           VARCHAR2(50) NOT NULL UNIQUE,
    FECHA_ORDEN            TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    PROVEEDOR_ID           NUMBER NOT NULL,
    EMPRESA_ID             NUMBER NOT NULL,
    SUCURSAL_ID            NUMBER NOT NULL,
    ESTADO                 VARCHAR2(20) DEFAULT 'PENDIENTE' 
        CHECK (ESTADO IN ('PENDIENTE', 'CONFIRMADA', 'ENTREGADA', 'CANCELADA')),
    TOTAL_BASE             NUMBER(12,2) DEFAULT 0,
    IMPUESTO               NUMBER(12,2) DEFAULT 0,
    TOTAL                  NUMBER(12,2) DEFAULT 0,
    OBSERVACIONES          VARCHAR2(1000),
    FECHA_ENTREGA_ESPERADA DATE,
    SOLICITADO_POR         NUMBER,
    FECHA_CREACION         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    CREADO_POR             NUMBER,
    FECHA_MODIFICACION     TIMESTAMP WITH TIME ZONE,
    MODIFICADO_POR         NUMBER,
    
    CONSTRAINT FK_OC_PROVEEDOR FOREIGN KEY (PROVEEDOR_ID)
        REFERENCES ODO_PROVEEDORES(PROVEEDOR_ID),
    CONSTRAINT FK_OC_EMPRESA FOREIGN KEY (EMPRESA_ID)
        REFERENCES ODO_EMPRESAS(EMPRESA_ID),
    CONSTRAINT FK_OC_SUCURSAL FOREIGN KEY (SUCURSAL_ID)
        REFERENCES ODO_SUCURSALES(SUCURSAL_ID),
    CONSTRAINT FK_OC_SOLICITADO_POR FOREIGN KEY (SOLICITADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID),
    CONSTRAINT FK_OC_CREADO_POR FOREIGN KEY (CREADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID),
    CONSTRAINT FK_OC_MODIFICADO_POR FOREIGN KEY (MODIFICADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID)
)
;;;
COMMENT ON TABLE ODO_ORDENES_COMPRA IS 'Órdenes de compra/solicitudes de artículos'
;;;

-- ============================================================================
-- TABLA: ODO_DETALLES_OC
-- Detalle de artículos en las órdenes de compra
-- ============================================================================
CREATE TABLE ODO_DETALLES_OC (
    DETALLE_OC_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDEN_COMPRA_ID        NUMBER NOT NULL,
    ARTICULO_ID            NUMBER NOT NULL,
    CANTIDAD_SOLICITADA    NUMBER NOT NULL,
    CANTIDAD_RECIBIDA      NUMBER DEFAULT 0,
    PRECIO_UNITARIO        NUMBER(12,2) NOT NULL,
    SUBTOTAL               NUMBER(12,2) NOT NULL,
    OBSERVACIONES          VARCHAR2(500),
    
    CONSTRAINT FK_DOC_ORDEN FOREIGN KEY (ORDEN_COMPRA_ID)
        REFERENCES ODO_ORDENES_COMPRA(ORDEN_COMPRA_ID) ON DELETE CASCADE,
    CONSTRAINT FK_DOC_ARTICULO FOREIGN KEY (ARTICULO_ID)
        REFERENCES ODO_ARTICULOS(ARTICULO_ID),
    CONSTRAINT CHK_CANTIDAD_SOLICITADA CHECK (CANTIDAD_SOLICITADA > 0),
    CONSTRAINT CHK_CANTIDAD_RECIBIDA CHECK (CANTIDAD_RECIBIDA >= 0),
    CONSTRAINT CHK_PRECIO_UNITARIO CHECK (PRECIO_UNITARIO >= 0)
)
;;;
COMMENT ON TABLE ODO_DETALLES_OC IS 'Detalle de artículos por orden de compra'
;;;

-- ============================================================================
-- TABLA: ODO_RECEPCION_COMPRAS
-- Recepción y verificación de compras
-- ============================================================================
CREATE TABLE ODO_RECEPCION_COMPRAS (
    RECEPCION_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDEN_COMPRA_ID        NUMBER NOT NULL,
    NUMERO_RECEPCION       VARCHAR2(50) NOT NULL UNIQUE,
    FECHA_RECEPCION        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    ESTADO                 VARCHAR2(20) DEFAULT 'PENDIENTE' 
        CHECK (ESTADO IN ('PENDIENTE', 'COMPLETA', 'PARCIAL', 'RECHAZADA')),
    OBSERVACIONES          VARCHAR2(1000),
    RECIBIDO_POR           NUMBER,
    VERIFICADO_POR         NUMBER,
    FECHA_CREACION         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    CREADO_POR             NUMBER,
    FECHA_MODIFICACION     TIMESTAMP WITH TIME ZONE,
    MODIFICADO_POR         NUMBER,
    
    CONSTRAINT FK_REC_ORDEN FOREIGN KEY (ORDEN_COMPRA_ID)
        REFERENCES ODO_ORDENES_COMPRA(ORDEN_COMPRA_ID),
    CONSTRAINT FK_REC_RECIBIDO_POR FOREIGN KEY (RECIBIDO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID),
    CONSTRAINT FK_REC_VERIFICADO_POR FOREIGN KEY (VERIFICADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID),
    CONSTRAINT FK_REC_CREADO_POR FOREIGN KEY (CREADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID),
    CONSTRAINT FK_REC_MODIFICADO_POR FOREIGN KEY (MODIFICADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID)
)
;;;
COMMENT ON TABLE ODO_RECEPCION_COMPRAS IS 'Recepción de artículos de órdenes de compra'
;;;

-- ============================================================================
-- TABLA: ODO_FACTURA_COMPRA
-- Facturas de proveedores
-- ============================================================================
CREATE TABLE ODO_FACTURA_COMPRA (
    FACTURA_COMPRA_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO_FACTURA         VARCHAR2(50) NOT NULL,
    FECHA_FACTURA          DATE NOT NULL,
    PROVEEDOR_ID           NUMBER NOT NULL,
    ORDEN_COMPRA_ID        NUMBER,
    EMPRESA_ID             NUMBER NOT NULL,
    SUCURSAL_ID            NUMBER NOT NULL,
    ESTADO                 VARCHAR2(20) DEFAULT 'RECIBIDA' 
        CHECK (ESTADO IN ('RECIBIDA', 'PROCESADA', 'PAGADA', 'ANULADA')),
    MONEDA                 VARCHAR2(10) DEFAULT 'PYG',
    TOTAL_BASE             NUMBER(12,2) DEFAULT 0,
    IMPUESTO_IVA           NUMBER(12,2) DEFAULT 0,
    TOTAL_GENERAL          NUMBER(12,2) DEFAULT 0,
    CONDICION_PAGO         VARCHAR2(100),
    FECHA_VENCIMIENTO      DATE,
    OBSERVACIONES          VARCHAR2(1000),
    ARCHIVO_ADJUNTO        VARCHAR2(500),
    REGISTRADO_POR         NUMBER,
    FECHA_CREACION         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    CREADO_POR             NUMBER,
    FECHA_MODIFICACION     TIMESTAMP WITH TIME ZONE,
    MODIFICADO_POR         NUMBER,
    
    CONSTRAINT FK_FC_PROVEEDOR FOREIGN KEY (PROVEEDOR_ID)
        REFERENCES ODO_PROVEEDORES(PROVEEDOR_ID),
    CONSTRAINT FK_FC_ORDEN FOREIGN KEY (ORDEN_COMPRA_ID)
        REFERENCES ODO_ORDENES_COMPRA(ORDEN_COMPRA_ID),
    CONSTRAINT FK_FC_EMPRESA FOREIGN KEY (EMPRESA_ID)
        REFERENCES ODO_EMPRESAS(EMPRESA_ID),
    CONSTRAINT FK_FC_SUCURSAL FOREIGN KEY (SUCURSAL_ID)
        REFERENCES ODO_SUCURSALES(SUCURSAL_ID),
    CONSTRAINT FK_FC_REGISTRADO_POR FOREIGN KEY (REGISTRADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID),
    CONSTRAINT FK_FC_CREADO_POR FOREIGN KEY (CREADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID),
    CONSTRAINT FK_FC_MODIFICADO_POR FOREIGN KEY (MODIFICADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID),
    CONSTRAINT UQ_FACTURA_PROVEEDOR UNIQUE (NUMERO_FACTURA, PROVEEDOR_ID, FECHA_FACTURA)
)
;;;
COMMENT ON TABLE ODO_FACTURA_COMPRA IS 'Facturas de proveedores de artículos'
;;;

-- ============================================================================
-- TABLA: ODO_FACTURA_COMPRA_DET
-- Detalle de items en facturas de compra
-- ============================================================================
CREATE TABLE ODO_FACTURA_COMPRA_DET (
    FACTURA_COMPRA_DET_ID  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FACTURA_COMPRA_ID      NUMBER NOT NULL,
    ARTICULO_ID            NUMBER NOT NULL,
    CANTIDAD               NUMBER NOT NULL,
    PRECIO_UNITARIO        NUMBER(12,2) NOT NULL,
    SUBTOTAL               NUMBER(12,2) NOT NULL,
    PORCENTAJE_IVA         NUMBER(5,2) DEFAULT 0,
    MONTO_IVA              NUMBER(12,2) DEFAULT 0,
    TOTAL_ITEM             NUMBER(12,2) NOT NULL,
    OBSERVACIONES          VARCHAR2(500),
    
    CONSTRAINT FK_FCD_FACTURA FOREIGN KEY (FACTURA_COMPRA_ID)
        REFERENCES ODO_FACTURA_COMPRA(FACTURA_COMPRA_ID) ON DELETE CASCADE,
    CONSTRAINT FK_FCD_ARTICULO FOREIGN KEY (ARTICULO_ID)
        REFERENCES ODO_ARTICULOS(ARTICULO_ID),
    CONSTRAINT CHK_FCD_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT CHK_FCD_PRECIO CHECK (PRECIO_UNITARIO >= 0)
)
;;;
COMMENT ON TABLE ODO_FACTURA_COMPRA_DET IS 'Detalle de artículos en facturas de compra de proveedores'
;;;

-- ============================================================================
-- TABLA: ODO_INVENTARIO
-- Control de inventario/stock de artículos
-- ============================================================================
CREATE TABLE ODO_INVENTARIO (
    INVENTARIO_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ARTICULO_ID            NUMBER NOT NULL UNIQUE,
    EMPRESA_ID             NUMBER NOT NULL,
    SUCURSAL_ID            NUMBER NOT NULL,
    CANTIDAD_ACTUAL        NUMBER DEFAULT 0,
    CANTIDAD_MINIMA        NUMBER DEFAULT 0,
    CANTIDAD_MAXIMA        NUMBER DEFAULT 0,
    UBICACION              VARCHAR2(200),
    COSTO_PROMEDIO         NUMBER(12,2) DEFAULT 0,
    ULTIMO_COSTO           NUMBER(12,2) DEFAULT 0,
    FECHA_ULTIMO_INGRESO   DATE,
    FECHA_ULTIMO_EGRESO    DATE,
    FECHA_ULTIMA_AUDITORIA DATE,
    REQUIERE_REORDEN       CHAR(1) DEFAULT 'N' CHECK (REQUIERE_REORDEN IN ('S', 'N')),
    OBSERVACIONES          VARCHAR2(500),
    FECHA_CREACION         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    CREADO_POR             NUMBER,
    FECHA_MODIFICACION     TIMESTAMP WITH TIME ZONE,
    MODIFICADO_POR         NUMBER,
    
    CONSTRAINT FK_INV_ARTICULO FOREIGN KEY (ARTICULO_ID)
        REFERENCES ODO_ARTICULOS(ARTICULO_ID),
    CONSTRAINT FK_INV_EMPRESA FOREIGN KEY (EMPRESA_ID)
        REFERENCES ODO_EMPRESAS(EMPRESA_ID),
    CONSTRAINT FK_INV_SUCURSAL FOREIGN KEY (SUCURSAL_ID)
        REFERENCES ODO_SUCURSALES(SUCURSAL_ID),
    CONSTRAINT FK_INV_CREADO_POR FOREIGN KEY (CREADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID),
    CONSTRAINT FK_INV_MODIFICADO_POR FOREIGN KEY (MODIFICADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID),
    CONSTRAINT CHK_CANTIDAD_ACTUAL CHECK (CANTIDAD_ACTUAL >= 0)
)
;;;
COMMENT ON TABLE ODO_INVENTARIO IS 'Control de stock/inventario de artículos'
;;;
COMMENT ON COLUMN ODO_INVENTARIO.CANTIDAD_ACTUAL IS 'Cantidad disponible en stock'
;;;
COMMENT ON COLUMN ODO_INVENTARIO.REQUIERE_REORDEN IS 'Indica si es necesario hacer una nueva orden de compra'
;;;

-- ============================================================================
-- TABLA: ODO_MOVIMIENTOS_INVENTARIO
-- Registro de todas las transacciones de inventario (auditoría)
-- ============================================================================
CREATE TABLE ODO_MOVIMIENTOS_INVENTARIO (
    MOVIMIENTO_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ARTICULO_ID            NUMBER NOT NULL,
    EMPRESA_ID             NUMBER NOT NULL,
    SUCURSAL_ID            NUMBER NOT NULL,
    TIPO_MOVIMIENTO        VARCHAR2(20) NOT NULL 
        CHECK (TIPO_MOVIMIENTO IN ('ENTRADA', 'SALIDA', 'AJUSTE', 'DEVOLUCION')),
    CANTIDAD               NUMBER NOT NULL,
    REFERENCIA_ID          NUMBER, -- ID de factura, orden, etc.
    REFERENCIA_TIPO        VARCHAR2(50), -- FACTURA_COMPRA, ORDEN_COMPRA, TRATAMIENTO, etc.
    DESCRIPCION            VARCHAR2(500),
    SALDO_ANTERIOR         NUMBER,
    SALDO_POSTERIOR        NUMBER,
    REGISTRADO_POR         NUMBER,
    FECHA_MOVIMIENTO       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    FECHA_CREACION         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    
    CONSTRAINT FK_MOV_ARTICULO FOREIGN KEY (ARTICULO_ID)
        REFERENCES ODO_ARTICULOS(ARTICULO_ID),
    CONSTRAINT FK_MOV_EMPRESA FOREIGN KEY (EMPRESA_ID)
        REFERENCES ODO_EMPRESAS(EMPRESA_ID),
    CONSTRAINT FK_MOV_SUCURSAL FOREIGN KEY (SUCURSAL_ID)
        REFERENCES ODO_SUCURSALES(SUCURSAL_ID),
    CONSTRAINT FK_MOV_REGISTRADO_POR FOREIGN KEY (REGISTRADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID)
)
;;;
COMMENT ON TABLE ODO_MOVIMIENTOS_INVENTARIO IS 'Registro de auditoría de todos los movimientos de inventario'
;;;

-- ============================================================================
-- ÍNDICES PARA OPTIMIZACIÓN DE QUERIES
-- ============================================================================
CREATE INDEX IDX_ARTICULOS_CATEGORIA ON ODO_ARTICULOS(CATEGORIA_ID)
;;;
CREATE INDEX IDX_ARTICULOS_ACTIVO ON ODO_ARTICULOS(ACTIVO)
;;;
CREATE INDEX IDX_PROVEEDORES_ACTIVO ON ODO_PROVEEDORES(ACTIVO)
;;;
CREATE INDEX IDX_PROVEEDORES_RUC ON ODO_PROVEEDORES(RUC)
;;;
CREATE INDEX IDX_ORDENES_ESTADO ON ODO_ORDENES_COMPRA(ESTADO)
;;;
CREATE INDEX IDX_ORDENES_PROVEEDOR ON ODO_ORDENES_COMPRA(PROVEEDOR_ID)
;;;
CREATE INDEX IDX_ORDENES_EMPRESA ON ODO_ORDENES_COMPRA(EMPRESA_ID)
;;;
CREATE INDEX IDX_ORDENES_FECHA ON ODO_ORDENES_COMPRA(FECHA_ORDEN)
;;;
CREATE INDEX IDX_FACTURA_COMPRA_ESTADO ON ODO_FACTURA_COMPRA(ESTADO)
;;;
CREATE INDEX IDX_FACTURA_COMPRA_PROVEEDOR ON ODO_FACTURA_COMPRA(PROVEEDOR_ID)
;;;
CREATE INDEX IDX_FACTURA_COMPRA_FECHA ON ODO_FACTURA_COMPRA(FECHA_FACTURA)
;;;
CREATE INDEX IDX_FACTURA_COMPRA_EMPRESA ON ODO_FACTURA_COMPRA(EMPRESA_ID)
;;;
CREATE INDEX IDX_INVENTARIO_EMPRESA ON ODO_INVENTARIO(EMPRESA_ID)
;;;
CREATE INDEX IDX_INVENTARIO_BAJO_STOCK ON ODO_INVENTARIO(REQUIERE_REORDEN)
;;;
CREATE INDEX IDX_MOVIMIENTOS_ARTICULO ON ODO_MOVIMIENTOS_INVENTARIO(ARTICULO_ID)
;;;
CREATE INDEX IDX_MOVIMIENTOS_FECHA ON ODO_MOVIMIENTOS_INVENTARIO(FECHA_MOVIMIENTO)
;;;
CREATE INDEX IDX_MOVIMIENTOS_TIPO ON ODO_MOVIMIENTOS_INVENTARIO(TIPO_MOVIMIENTO)
;;;

-- ============================================================================
-- SECUENCIAS PARA NUMERACIÓN
-- ============================================================================
CREATE SEQUENCE SEQ_NUMERO_ORDEN_COMPRA START WITH 1000 INCREMENT BY 1
;;;
CREATE SEQUENCE SEQ_NUMERO_RECEPCION START WITH 1000 INCREMENT BY 1
;;;

-- Commit
COMMIT
;;;
