-- Continuar creación del módulo de caja (tabla movimientos + índices + datos)

CREATE TABLE ODO_MOVIMIENTOS_CAJA (
    MOVIMIENTO_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CAJA_ID          NUMBER NOT NULL,
    TIPO             CHAR(7) NOT NULL CHECK (TIPO IN ('INGRESO', 'EGRESO')),
    CATEGORIA_ID     NUMBER,
    CONCEPTO         VARCHAR2(500) NOT NULL,
    MONTO            NUMBER(15,2) NOT NULL,
    REFERENCIA       VARCHAR2(200),
    FACTURA_ID       NUMBER,
    REGISTRADO_POR   NUMBER NOT NULL,
    FECHA_HORA       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    OBSERVACIONES    VARCHAR2(1000),
    CONSTRAINT FK_MOVCAJA_CAJA FOREIGN KEY (CAJA_ID)
        REFERENCES ODO_CAJAS(CAJA_ID),
    CONSTRAINT FK_MOVCAJA_CATEGORIA FOREIGN KEY (CATEGORIA_ID)
        REFERENCES ODO_CATEGORIAS_MOVIMIENTO_CAJA(CATEGORIA_ID),
    CONSTRAINT FK_MOVCAJA_REGISTRADO FOREIGN KEY (REGISTRADO_POR)
        REFERENCES ODO_USUARIOS(USUARIO_ID),
    CONSTRAINT CHK_MOVCAJA_MONTO CHECK (MONTO > 0)
)
/
COMMENT ON TABLE ODO_MOVIMIENTOS_CAJA IS 'Registros de ingresos y egresos de caja'
/

CREATE INDEX IDX_CAJAS_EMPRESA ON ODO_CAJAS(EMPRESA_ID)
/
CREATE INDEX IDX_CAJAS_USUARIO ON ODO_CAJAS(USUARIO_ASIGNADO_ID)
/
CREATE INDEX IDX_CAJAS_ESTADO ON ODO_CAJAS(ESTADO)
/
CREATE INDEX IDX_MOVCAJA_CAJA ON ODO_MOVIMIENTOS_CAJA(CAJA_ID)
/
CREATE INDEX IDX_MOVCAJA_FECHA ON ODO_MOVIMIENTOS_CAJA(FECHA_HORA)
/
CREATE INDEX IDX_MOVCAJA_TIPO ON ODO_MOVIMIENTOS_CAJA(TIPO)
/

INSERT INTO ODO_CATEGORIAS_MOVIMIENTO_CAJA (NOMBRE, TIPO, DESCRIPCION, CREADO_POR)
VALUES ('Cobro de consulta', 'INGRESO', 'Ingreso por consulta médica odontológica', 1)
/
INSERT INTO ODO_CATEGORIAS_MOVIMIENTO_CAJA (NOMBRE, TIPO, DESCRIPCION, CREADO_POR)
VALUES ('Cobro de tratamiento', 'INGRESO', 'Ingreso por tratamiento odontológico', 1)
/
INSERT INTO ODO_CATEGORIAS_MOVIMIENTO_CAJA (NOMBRE, TIPO, DESCRIPCION, CREADO_POR)
VALUES ('Cobro de factura', 'INGRESO', 'Pago de factura emitida', 1)
/
INSERT INTO ODO_CATEGORIAS_MOVIMIENTO_CAJA (NOMBRE, TIPO, DESCRIPCION, CREADO_POR)
VALUES ('Otros ingresos', 'INGRESO', 'Ingresos varios no clasificados', 1)
/
INSERT INTO ODO_CATEGORIAS_MOVIMIENTO_CAJA (NOMBRE, TIPO, DESCRIPCION, CREADO_POR)
VALUES ('Compra de materiales', 'EGRESO', 'Compra de materiales e insumos dentales', 1)
/
INSERT INTO ODO_CATEGORIAS_MOVIMIENTO_CAJA (NOMBRE, TIPO, DESCRIPCION, CREADO_POR)
VALUES ('Pago de servicios', 'EGRESO', 'Pago de servicios (luz, agua, teléfono, etc.)', 1)
/
INSERT INTO ODO_CATEGORIAS_MOVIMIENTO_CAJA (NOMBRE, TIPO, DESCRIPCION, CREADO_POR)
VALUES ('Pago de personal', 'EGRESO', 'Pago de sueldos y salarios', 1)
/
INSERT INTO ODO_CATEGORIAS_MOVIMIENTO_CAJA (NOMBRE, TIPO, DESCRIPCION, CREADO_POR)
VALUES ('Gastos varios', 'EGRESO', 'Egresos varios no clasificados', 1)
/
COMMIT
/
